apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vitalam-service-template.fullname" . }}-config
  labels:
    {{- include "vitalam-service-template.labels" . | nindent 4 }}
data:
  port: {{ .Values.config.port | quote }}
  apiHost: {{ .Values.config.apiHost | quote }}
  userUri: {{ .Values.config.userUri | quote }}
